/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Stocks;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Sectors extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Sectors() {
        initComponents();
        fetch();
    }
    Connection conn;
    PreparedStatement pre;
    
    private void clear(){
        txtsector.setText(null);  
    }
    
    private void fetch(){
        try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
    
             String sql = "select * from sectors";
            
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             DefaultTableModel dl = (DefaultTableModel)tblsector.getModel();
             dl.setRowCount(0);
             while(rs.next()){
                 Vector v = new Vector();
                 v.add(rs.getString("sectorid"));
                 v.add(rs.getString("sector"));
                 dl.addRow(v);
             }                
        }
        catch(Exception e){
                     System.out.println("error" + e);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtsector = new javax.swing.JTextField();
        txtcatadd = new javax.swing.JButton();
        txtcathome = new javax.swing.JButton();
        txtcatclear = new javax.swing.JButton();
        txtcatupdate = new javax.swing.JButton();
        txtcatdelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsector = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Sector");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(283, 283, 283))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD SECTOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sector Name");

        txtsector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsectorActionPerformed(evt);
            }
        });

        txtcatadd.setBackground(new java.awt.Color(255, 51, 51));
        txtcatadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcatadd.setForeground(new java.awt.Color(255, 255, 255));
        txtcatadd.setText("ADD");
        txtcatadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcataddActionPerformed(evt);
            }
        });

        txtcathome.setBackground(new java.awt.Color(255, 51, 51));
        txtcathome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcathome.setForeground(new java.awt.Color(255, 255, 255));
        txtcathome.setText("HOME");
        txtcathome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcathomeActionPerformed(evt);
            }
        });

        txtcatclear.setBackground(new java.awt.Color(255, 51, 51));
        txtcatclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcatclear.setForeground(new java.awt.Color(255, 255, 255));
        txtcatclear.setText("CLEAR");
        txtcatclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatclearActionPerformed(evt);
            }
        });

        txtcatupdate.setBackground(new java.awt.Color(255, 51, 51));
        txtcatupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcatupdate.setForeground(new java.awt.Color(255, 255, 255));
        txtcatupdate.setText("UPDATE");
        txtcatupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatupdateActionPerformed(evt);
            }
        });

        txtcatdelete.setBackground(new java.awt.Color(255, 51, 51));
        txtcatdelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcatdelete.setForeground(new java.awt.Color(255, 255, 255));
        txtcatdelete.setText("DELETE");
        txtcatdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatdeleteActionPerformed(evt);
            }
        });

        tblsector.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sector ID", "Sector"
            }
        ));
        tblsector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsectorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsector);
        if (tblsector.getColumnModel().getColumnCount() > 0) {
            tblsector.getColumnModel().getColumn(0).setPreferredWidth(4);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(txtsector, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtcatadd)
                        .addGap(18, 18, 18)
                        .addComponent(txtcatupdate)
                        .addGap(18, 18, 18)
                        .addComponent(txtcatdelete)
                        .addGap(18, 18, 18)
                        .addComponent(txtcatclear)
                        .addGap(18, 18, 18)
                        .addComponent(txtcathome)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtsector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcatadd)
                                    .addComponent(txtcatdelete)
                                    .addComponent(txtcatupdate)
                                    .addComponent(txtcatclear)
                                    .addComponent(txtcathome)))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsectorActionPerformed

    private void txtcataddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcataddActionPerformed
        // TODO add your handling code here:
        String sector = txtsector.getText();
           
           try{
               Class.forName("com.mysql.jdbc.Driver");
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
               
               pre = conn.prepareStatement("insert into sectors (sector) values (?)");
               pre.setString(1, sector);
               
               int rs = pre.executeUpdate();
               
               if(rs==1){
                   JOptionPane.showMessageDialog(null, "sector added successfull");
                   fetch();
                   clear();
                   txtsector.requestFocus();
               }
           }
           catch(Exception e){
               System.out.println("error" + e);
           }
    }//GEN-LAST:event_txtcataddActionPerformed

    private void txtcathomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcathomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcathomeActionPerformed

    private void txtcatclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_txtcatclearActionPerformed

    private void txtcatupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dl = (DefaultTableModel)tblsector.getModel();
        int index = tblsector.getSelectedRow();
        int id = Integer.parseInt(dl.getValueAt(index,0).toString());
            
        String category = txtsector.getText();
                try{
            Class.forName("com.mysql.jdbc.Driver");
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
               
               pre = conn.prepareStatement("update sectors set sector=? where sectorid=?");
               pre.setString(1, category);
               pre.setInt(2, id);
               
               int rs = pre.executeUpdate();
               
               if(rs==1){
                   JOptionPane.showMessageDialog(null, "sector updated successfull");
                   fetch();
                   clear();
                   txtsector.requestFocus();
               }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtcatupdateActionPerformed

    private void txtcatdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatdeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dl = (DefaultTableModel)tblsector.getModel();
        int index = tblsector.getSelectedRow();
        int id = Integer.parseInt(dl.getValueAt(index,0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null,"do u want to delete","warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult==JOptionPane.YES_OPTION){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
            String sql = "delete from sectors where sectorid='"+id+"'";
            System.out.println(sql);
            Statement stmt = (Statement) con.createStatement();
               int rs = stmt.executeUpdate(sql);
               System.out.println(rs);

               if(rs==1){
                   JOptionPane.showMessageDialog(this,"Successfully deleted");
                   fetch();
                   clear();
                   txtsector.requestFocus();
               }
            
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_txtcatdeleteActionPerformed

    private void tblsectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsectorMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dl=(DefaultTableModel)tblsector.getModel();
        int index=tblsector.getSelectedRow();
        txtsector.setText(dl.getValueAt(index,1).toString());
    }//GEN-LAST:event_tblsectorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sectors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsector;
    private javax.swing.JButton txtcatadd;
    private javax.swing.JButton txtcatclear;
    private javax.swing.JButton txtcatdelete;
    private javax.swing.JButton txtcathome;
    private javax.swing.JButton txtcatupdate;
    private javax.swing.JTextField txtsector;
    // End of variables declaration//GEN-END:variables
}
